config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'd'
  resources :users, :only => [:show]

  get '/messages', to: 'users#messages'

  root to: 'pages#home'

  resources :chats, only: [:create, :show, :index] do
    member do
      patch :favourites
      patch :archive
    end
    collection do
      get :saved
      get :archived
    end

    resources :messages, only: [:create]
  end

  resources :artists do
    collection do
      get :top
    end
    member do
    delete :delete_image_attachment

    end
    resources :services, only: [:new, :create]
    resources :bookings, only: [:new]


    resources :working_hours, only: [:new, :create]


  end

  resources :bookings do
    collection do
      get :all
    end
    member do
      get :selectdate
      get :selecttime
    end
    resources :services_bookings, only: [:new]
  end

  resources :services, only: [:destroy, :edit, :update]
  resources :working_hours, only: [:destroy, :edit, :update]
  resources :bookings, only: [:edit, :update, :create, :destroy, :index ] do
  resources :services_bookings, only: [:create]
  resources :reviews, only: [:new, :create, :index]
    collection do
      get :all
      get :pending
      get :confirmed
      get :declined
      get :cancelled
    end
    member do
      get :details
      patch :confirm
      patch :decline
      patch :cancel
    end
  end

  resources :artists do
    collection do
      get :top
    end
    resources :services, only: [:new, :create]
    resources :bookings, only: [:new, :show]

  end

  resources :bookings do
    resources :services_bookings, only: [:new]
  end

  resources :bookings do
    member do
      get :selectdate
      get :selecttime
    end
  end


  resources :reviews, only: [:edit, :update]
  resources :bookmarks, only: [:index, :create, :destroy] do
    collection { post :sort }
  end
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates :description, presence: true
  belongs_to :user
  has_many_attached :photos, dependent: :destroy
  has_many :services, dependent: :destroy
  has_many :services_bookings, through: :services, dependent: :destroy
  has_many :bookings
  has_many :chats
  has_many :messages, through: :chats, dependent: :destroy
  has_one :working_hour
  scope :filter_by_category, -> (category) { where category: category }

  def rating
    reviews = []
    bookings.each do |booking|
      booking.reviews.each do |review|
        review.present?
        reviews << review
      end
    end

    rating_sum = 0
    reviews.each { |review| rating_sum += review.rating }
    rating_sum.zero? ? average_rating = 0 : average_rating = rating_sum / reviews.count
    average_rating
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  before_action :set_artist, only: [:show, :edit, :update, :destroy]


  def index
    # Search by artist location.
    if params[:query].present?
      # Can only use Geocoder near method on User class.
      @users = User.near(params[:query])
      @artists = @users.map { |user| user.artist if user.artist.present? }
      @artists.delete(nil)
      category_filter(@artists) if params[:artist].present?
      artist_users(@artists)
      markers(@artist_users)
      @categoryselect = { prompt: true, prompt: "Category" }
      # raise
    # Search by artist information.
    elsif
      params[:query_artist].present?
      sql_query = " \
        artists.description @@ :query \
        OR artists.qualifications @@ :query \
        OR users.username @@ :query \
        OR users.first_name @@ :query \
        OR users.last_name @@ :query \
      "
      @artists = Artist.joins(:user).where(sql_query, query: "%#{params[:query_artist]}%")
      category_filter(@artists) if params[:artist].present?
      artist_users(@artists)
      markers(@artist_users)
      @categoryselect = { prompt: true, prompt: "Category" }
    # No search.
    else
      @artists = Artist.all
      category_filter(@artists) if params[:artist].present?
      artist_users(@artists)
      markers(@artist_users)
      @categoryselect = { prompt: true, prompt: "Category" }
    end
  end

  def artist_users(artists)
    @artist_users = []
    @artists.each do |artist|
      artist.user.latitude.present? && artist.user.longitude.present?
      @artist_users << artist.user
    end
    @artist_users
  end

  def markers(artist_users)
    @markers = @artist_users.map do |user|
      {
        lat: user.latitude,
        lng: user.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { user: user }),
      }
    end
    @markers
  end

  def category_filter(artists)
    if params[:artist][:category] != ""
      @artists = @artists.select { |artist| artist.category == params[:artist][:category] }
    end
    @artists
  end

  def new
    @artist = Artist.new
  end

  def show
    @chat = Chat.where(artist: current_user.artist, user: @artist.user).or(Chat.where(artist: @artist, user: current_user)).first if user_signed_in?
    @bookings = @artist.bookings
    @reviews = []
    @bookings.each do |booking|
      booking.reviews.each do |review|
        review.present?
        @reviews << review
      end
    end

    @rating_sum = 0
    @reviews.each { |review| @rating_sum += review.rating }
    @rating_sum.zero? ? @average_rating = 0 : @average_rating = @rating_sum / @reviews.count
  end

  def create
    @artist = Artist.new(artist_params)
    @artist.user = current_user
    if @artist.save
      redirect_to artist_path(@artist)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @artist.update(artist_params)
    redirect_to edit_artist_path(@artist)
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end

  def top
    @blobs = Bookmark.group(:active_storage_blob_id)
      .select(:active_storage_blob_id)
      .count # Gives an array of hashes, each one containing asb_id and count
      .sort_by { |_k, v| - v } # Sorts by count
      .map { |k, v| { blob: ActiveStorage::Blob.find(k), count: v } } # Transforms them into a nicer hash to be used on the view with the full blob instead of just the id and it's count
  end

  def delete_image_attachment
  @image = ActiveStorage::Attachment.find(params[:id])
  @image.purge
  redirect_to edit_artist_path(current_user.artist, anchor: "photos-div")
end

  private

  def set_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:description, :qualifications, :category, photos: [])
  end
end

app/views/artists/_info_window.html.erb
<div class="info-window">
  <%= link_to artist_path(user.artist) do %>
  <%= cl_image_tag user.photo.key, height: 60, width: 60, gravity: :face, crop: :fill, style: "border-radius: 100%" %>
  <div style="text-align: left">
    <br><h6><%= user.username %></h6>
    <strong><%= user.artist.category %></strong>
    <br><%= user.address %>
  </div>
  <% end %>
</div>

app/views/artists/_map_modal.html.erb
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="map">
        <div id="map"
         style="width: 100%; height: 600px;"
         data-markers="<%= @markers.to_json %>"
         data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
        <div class="map-close">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true"><i class="fas fa-times" style="color: black"></i></span>
          </button>
        </div>
     </div>
    </div>
  </div>
</div>

app/views/artists/edit.html.erb
<div class="d-flex align-items-center justify-content-between p-3 bg-white">
    <%= link_to artist_path(current_user.artist) do %>
    <i class="fas fa-chevron-left"></i>
  <% end %>

    <h6 class = "text-center"> update your page details </h6>
  <%= link_to user_path(current_user) do %>
  <%= cl_image_tag current_user.photo.key, height: 48, width: 48, gravity: :face, crop: :fill, radius: :max, class: "rounded-circle" %>
  <% end %>
  </div>



  <div class="container">
  <div class="row">
    <div class="col-12">
      <div class="form-login">

      <%= simple_form_for(@artist) do |f| %>
        <%= f.input :description, :label => "Tell Us About Yourself" %>
        <%= f.input :qualifications, :label => "List any career highlights, qualifications & work experience..." %>
        <%= f.input :category, collection: ["Makeup Artist", "Makeup & Hair Stylist", "Hair Stylist", "Nail Technician", "Waxing", "Tanning", "Skin & Beauty Treatments", "Multi Service"], :label => "What field are you in?" %>

       <div class="dropzone dropzone-default dz-clickable" data-controller="dropzone" data-dropzone-max-file-size="2" data-dropzone-max-files="8">
          <%= f.input :photos, as: :file, label: false, input_html: { multiple: true, direct_upload: true, data: { target: "dropzone.input" } } %>
          <div class="dropzone-msg dz-message needsclick">
            <h5 class="dropzone-msg-title" style="color: grey;"><i class="fas fa-plus" style="color: grey; font-size: 16px;"></i> Upload Photos </h5>

          </div>
        </div>



        <br>
        <h6> Order your photos by dragging & dropping them into position </h6><br>
        <div data-controller="photos">
          <ul id="photos-list" class=" photo-grid grid-list" data-action="drop->photos#sort">
          <% @artist.photos.order("position").each do |photo| %>
            <li class="photo-item grid-item" data-photo-id="<%= photo.id %>">
              <div id="photos-div" class="position-div">
              <%= cl_image_tag photo.key,  width: 400, height: 400, crop: :fill, class: "w-100 bookmark-img", style: "border-radius: 20px;" %>
                <%= link_to delete_image_attachment_artist_url(photo.id),
                method: :delete,
                remote: true,
                data: { confirm: 'Please confirm you wish to remove this photo from your profile' }  do %>
                <i class="fas fa-trash delete-icon-edit"></i>
              <% end %>
              </div>
            </li>
          <% end %>
          </ul>
        </div>
        <%= f.button :submit, 'Update Profile', class: 'btn btn-warning' %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/artists/index.html.erb
<div class="d-flex align-items-center justify-content-between p-3 bg-white">
  <%= link_to root_path do %>
    <i class="fas fa-chevron-left"></i>
  <% end %>

  <%= form_tag artists_path, method: :get do %>
    <%= collection_select(:artist, :category, @artists.uniq { |artist| artist.category }, :category, :category, @categoryselect, html_options = { class: "category-filter", id: "category-selector", onchange: "this.form.submit()" }) %>
    <% if params[:query].present? %>
      <%= link_to artists_path(params: { query: params[:query] }) do %>
      <i class="fa fa-times cross" aria-hidden="true"></i>
        <% end %>
    <% elsif params[:query_artist].present? %>
      <%= link_to artists_path(params: { query_artist: params[:query_artist] }) do %>
      <i class="fa fa-times cross" aria-hidden="true"></i>
        <% end %>
    <% else %>
      <%= link_to artists_path do %>
        <i class="fa fa-times cross" aria-hidden="true"></i>
        <% end %>
    <% end %>
    <%= hidden_field_tag :query, params[:query] %>
    <%= hidden_field_tag :query_artist, params[:query_artist] %>
  <% end %>
</div>

<br>
<% @artists.each do |artist| %>
  <%= link_to artist_path(artist) do %>
    <div class="index-card">
      <%= cl_image_tag artist.photos.order("position")[0].key, height: 200, width: 400, gravity: :face, crop: :fill, class: "card-img-top fill-photo", style: "border-top-left-radius: 8px; border-top-right-radius: 8px;" %>
        <div class="pt-3 pl-3">
         <h6><%= artist.user.first_name %> <%= artist.user.last_name %></h6>
         <p><%= artist.category if artist.category %></p>
          <% artist.rating.times do %>
            <%= content_tag(:i, "", class: "fas fa-star rating") %>
          <% end %>
        </div>
      <div class="pl-3">
        <p><i class="fas fa-map-marker-alt fa-lg pr-1"></i> <%= artist.user.address %></p>
      </div>
    </div>
  <% end %>
  <br>
<% end %>

<div class="map-btn-position">
  <button type="button" class="map-btn" data-toggle="modal" data-target=".bd-example-modal-lg"><i class="far fa-map" style="color: white"></i></button>
</div>

<%= render 'artists/map_modal' %>

app/views/artists/new.html.erb
<div class="d-flex align-items-center justify-content-between p-3 bg-white">
    <%= link_to user_path(current_user) do %>
    <i class="fas fa-chevron-left"></i>
  <% end %>

  <h6 class = "text-center"> makeup artist registration</h6>
  <%= link_to user_path(current_user) do %>
  <%= cl_image_tag current_user.photo.key, height: 48, width: 48, gravity: :face, crop: :fill, radius: :max, class: "rounded-circle" %>
  <% end %>
  </div>

  <div class="container">
  <div class="row">
    <div class="col-12">
      <div class="form-login">
        <%= simple_form_for(@artist) do |f| %>
          <%= f.input :description, :label => "Tell Us About Yourself" %>
          <%= f.input :qualifications, :label => "List any career highlights, qualifications & work experience..." %>
          <%= f.input :category, collection: ["Makeup Artist", "Makeup & Hair Stylist", "Hair Stylist", "Nail Technician", "Waxing", "Tanning", "Skin & Beauty Treatments", "Multi Service"], :label => "What field are you in?" %>

         <div class="dropzone dropzone-default dz-clickable" data-controller="dropzone" data-dropzone-max-file-size="2" data-dropzone-max-files="8">
            <%= f.input :photos, as: :file, label: false, input_html: { multiple: true, direct_upload: true, data: { target: "dropzone.input" } } %>
            <div class="dropzone-msg dz-message needsclick">
              <h5 class="dropzone-msg-title" style="color: grey;"><i class="fas fa-plus" style="color: grey; font-size: 16px;"></i> Upload Photos </h5>

            </div>
          </div>
          <br>
          <%= f.submit class: "btn btn-warning"%>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/artists/show.html.erb
  <div class="d-flex align-items-center justify-content-between p-3 bg-white">

    <%= link_to :back do %>
      <i class="fas fa-chevron-left"></i>
    <% end %>
    <h6><%= @artist.user.username %></h6>
    <div>
    <% if current_user == @artist.user %>
      <%= link_to edit_artist_path(@artist) do %>
        <i class="fas fa-pen-square"></i>
        <% end %>
        <% elsif %>
        <% user_signed_in? %>

        <% if @chat.present? && @chat.messages.empty? %>
        <%= link_to chat_path(@chat) do %>
        <i class="far fa-comments"></i>
        <% end %>
        <% elsif @chat.present? %>
        <%= link_to chat_path(@chat, anchor: "message-#{@chat.messages.last.id}") do %>
        <i class="far fa-comments"></i>
        <% end %>
        <% else %>
        <%= link_to chats_path(@artist), method: :post do %>
         <i class="far fa-comments"></i>
         <% end %>
        <% end %>
        <% else %>
        <div>
        </div>
      <% end %>
  </div>
    </div>

<div class="container bottom-padding mt-3">

  <div class="bg-white p-2" style="border-radius: 20px 20px 20px 20px; text-align: center;">
    <%= cl_image_tag @artist.user.photo.key, height: 100, width: 100, gravity: :face, crop: :fill, radius: :max, class: "mt-3 mr-3" %>
    <br><br>
    <h4><%= @artist.user.first_name %> <%= @artist.user.last_name %></h4>
    <h6><i class="fas fa-map-marker-alt fa-lg pr-1"></i> <%= @artist.user.address %></h6>
    <h6><% if @average_rating == 0 %>
    <% else %>
      <% @average_rating.times do %>
       <%= content_tag(:i, "", class: "fas fa-star rating") %>
      <% end %>
      <%= @average_rating %> (<%= @reviews.count %>)
    <% end %>
    </h6>
    <p style="padding: 20px; margin-top: 5px;"><%= @artist.description %></p>

    <%= render 'shared/show_carousel' %>

    <div class="p-2" style="text-align: left;">
      <br>
      <h6>Services</h6>
      <%= render 'shared/show_accordion' %>
      <% if current_user == @artist.user %>
        <div style="margin-top: 12px;">
          <%= link_to new_artist_service_path(@artist) do %>
             <i class="far fa-plus-square ml-1 rating"></i> <small>Add a service</small>
          <% end %>
        </div>
      <% end %>
      <br><br>
      <%= link_to "Book #{@artist.user.first_name}", new_booking_path(artist_id: @artist), artist: @artist, method: :get, class: "btn book-btn" %>
      <hr></hr>
      <h6 style="margin-bottom: 16px;">Experience</h6>
      <p><%= @artist.qualifications %></p>
      <hr></hr>
      <div style="display: flex; justify-content: space-between">
      <h6 style="margin-bottom: 16px;">Working Hours</h6>
      <div>


      <% if current_user == @artist.user && @artist.working_hour.present? %>
        <%= link_to edit_working_hour_path(@artist.working_hour) do %>
          <i class="fas fa-pen-square rating ml-2"></i>
        <% end %>
        <%= link_to working_hour_path(@artist.working_hour), method: :delete, class: "delete" do %>
          <i class="fas fa-trash rating ml-2"></i>
        <% end %>
      <% end %>
      </div>
      </div>
      <% if @artist.working_hour.nil? && current_user == @artist.user %>
        <div style="margin-top: 12px;">
          <%= link_to new_artist_working_hour_path(@artist) do %>
            <i class="far fa-plus-square ml-1 rating"></i> <small>Add working hours</small>
          <% end %>
      <% end %>

      <% if @artist.working_hour.present? %>
      <table class="table table-borderless" style="width: 100%">
      <thead>
        <tr>
          <td scope="col">Day</th>
          <td scope="col"class="tdright">Start Time</th>
          <td scope="col" class="tdright">End Time </th>
        </tr>
      </thead>
      <tbody>
        <% first_day = Date.today.at_beginning_of_week %>
        <% days = 7.times.map {|x| first_day + x.days} %>
        <% days.each do |day| %>
        <tr>
          <td scope="row"><%= day.strftime("%A") %></th>
          <td class="tdright"><%= "-" if @artist.working_hour["#{day.strftime("%A").downcase}start_time"].nil? %><%= @artist.working_hour["#{day.strftime("%A").downcase}start_time"].strftime("%l:%M%P") if @artist.working_hour["#{day.strftime("%A").downcase}start_time"].present? %></td>
          <td class="tdright"><%= "-" if @artist.working_hour["#{day.strftime("%A").downcase}start_time"].nil? %><%= @artist.working_hour["#{day.strftime("%A").downcase}end_time"].strftime("%l:%M%P") if @artist.working_hour["#{day.strftime("%A").downcase}end_time"].present? %></td>
        </tr>
        <% end %>
      </tbody>
      </table>
      <% end %>


      <hr></hr>
      <h6 style="margin-bottom: 16px;">Reviews</h6>
      <% if @reviews.empty? %>
        <p>No reviews yet</p>
        <br>
      <% else %>
        <% @reviews.each do |review| %>
          <div class="d-flex">
            <%= cl_image_tag review.booking.user.photo.key, height: 60, width: 60, gravity: :face, crop: :fill, radius: :max, class: "rounded-circle mr-1" %>
            <div style="margin-left: 10px;">
              <strong><%= review.booking.user.username %></strong>
              <br><% (review.rating).times do %>
                <%= content_tag(:i, "", class: "fas fa-star rating") %>
              <% end %>
              <br><p><%= review.created_at.strftime("%d %B %Y") %></p>
            </div>
          </div>
          <p><%= review.content %></p>
          <% if review.booking.artist.user == current_user && review.reply.nil? %>
            <%= link_to "Reply to #{review.booking.user.username}", edit_review_path(review), method: :get, class: "small" %>
            <br>
          <% elsif %>
            <% review.booking.artist.user != current_user && review.reply.nil? %>
          <% else %>
            <div class="d-flex" style="border-left: 3px solid #e5e5e5; padding: 5px;">
              <%= cl_image_tag review.booking.artist.user.photo.key, height: 40, width: 40, gravity: :face, crop: :fill, radius: :max, class: "rounded-circle mr-1" %>
              <div style="margin-left: 10px;">
                <strong><%= review.booking.artist.user.username %></strong>
                <p><%= review.updated_at.strftime("%d %B %Y") %></p>
                <p><%= review.reply %></p>
              </div>
            </div>
          <% end %>
          <br>
        <% end %>
      <% end %>
    </div>
  </div>

</div>

app/views/artists/top.html.erb
<div class="container">


  <h3>Top Looks </h3>
  <div class="row">
    <% @blobs.each do |blob| %>
      <div class="col-sm-4 my-3">
        <div class="col-12" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.3)), url(<%= cl_image_path blob[:blob].key %>); height: 200px; background-position: center; background-size: cover; border: 1px solid black; position: relative;">
        </div>
        <p><%= blob[:count] %> Likes </p>
         <% if current_user.present? %>
        <% if current_user.has_bookmark?(blob[:blob]) %>
          <%= link_to bookmark_path(current_user.bookmark_of(blob[:blob])), method: :delete do %>
            <i class="fas fa-heart" style="color: red; position: absolute; top: 4px; right: 24px; font-size: 22px"></i>
          <% end %>
        <% else %>
          <%= link_to bookmarks_path(blob: blob[:blob]), method: :post do %>
            <i class="far fa-heart" style="color: red; position: absolute; top: 4px; right: 24px; font-size: 22px"></i>
          <% end %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>