config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'd'
  resources :users, :only => [:show]

  get '/messages', to: 'users#messages'

  root to: 'pages#home'

  resources :chats, only: [:create, :show, :index] do
    member do
      patch :favourites
      patch :archive
    end
    collection do
      get :saved
      get :archived
    end

    resources :messages, only: [:create]
  end

  resources :artists do
    collection do
      get :top
    end
    member do
    delete :delete_image_attachment

    end
    resources :services, only: [:new, :create]
    resources :bookings, only: [:new]


    resources :working_hours, only: [:new, :create]


  end

  resources :bookings do
    collection do
      get :all
    end
    member do
      get :selectdate
      get :selecttime
    end
    resources :services_bookings, only: [:new]
  end

  resources :services, only: [:destroy, :edit, :update]
  resources :working_hours, only: [:destroy, :edit, :update]
  resources :bookings, only: [:edit, :update, :create, :destroy, :index ] do
  resources :services_bookings, only: [:create]
  resources :reviews, only: [:new, :create, :index]
    collection do
      get :all
      get :pending
      get :confirmed
      get :declined
      get :cancelled
    end
    member do
      get :details
      patch :confirm
      patch :decline
      patch :cancel
    end
  end

  resources :artists do
    collection do
      get :top
    end
    resources :services, only: [:new, :create]
    resources :bookings, only: [:new, :show]

  end

  resources :bookings do
    resources :services_bookings, only: [:new]
  end

  resources :bookings do
    member do
      get :selectdate
      get :selecttime
    end
  end


  resources :reviews, only: [:edit, :update]
  resources :bookmarks, only: [:index, :create, :destroy] do
    collection { post :sort }
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one :artist, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_one_attached :photo
  has_many :chats, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :messages, through: :chats, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of   :first_name
  validates_presence_of   :last_name
  validates_presence_of   :address
  validates :username, uniqueness: true

  def has_bookmark?(blob)
    bookmarks.map(&:blob).include?(blob)
  end

  def bookmark_of(blob)
    bookmarks.find_by(active_storage_blob: blob)
  end

  def received_messages
    Message.joins(:chat).where(chats: { artist: self.artist}).or(Message.joins(:chat).where(chats: { user: self })).where.not(messages: { user: self })
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
  end

  def messages
    @messages = user_signed_in? ? current_user.received_messages : []

    respond_to do |format|
    format.html
    format.json { render json: { messages: @messages.where(read: false) } }
    end
  end
end

app/views/users/show.html.erb
<% if user_signed_in? %>
<div class="container bottom-padding mt-3">
  <div class="bg-white p-2" style="border-radius: 20px 20px 20px 20px; text-align: center;">

    <br>
    <h3><%= "Hello #{@user.first_name}" %></h3>
    <br>
    <div style="text-align: center">
      <%= cl_image_tag current_user.photo.key, height: 100, width: 100, gravity: :face, crop: :fill, radius: :max, class: "rounded-circle" %>

    </div >
    <br><p style="font-weight:bold; font-size:18px;"><%= @user.first_name %> <%= @user.last_name %></p>
    <p><i class="fas fa-map-marker-alt fa-lg pr-1"></i> <%= @user.address %></p>
    <p>Member since <%= @user.created_at.strftime("%d %B %Y") %></p>

    <br>
    <% if @user.artist.nil? %>
      <div class="nav-tile">
        <i class="fas fa-portrait"></i>
        <br>
        <%= link_to "Become an artist", new_artist_path %>
      </div>
    <% end %>

    <% unless @user.artist.nil? %>
      <div class="nav-tile">
        <i class="fas fa-portrait"></i>
        <br>
        <%= link_to "My artist page", artist_path(id: @user.artist) %>
      </div>
    <% end %>

    <div class="nav-tile">
      <i class="far fa-calendar-alt"></i>
      <br>
      <%= link_to "My bookings", bookings_path %>
    </div>

    <% unless @user.artist.nil? %>
      <div class="nav-tile">
        <i class="fas fa-people-arrows"></i>
        <br>
        <%= link_to "My jobs", all_bookings_path %>
      </div>
    <% end %>

    <div class="nav-tile">
      <i class="fas fa-cog"></i>
      <br>
      <%= link_to "Edit Account", edit_user_registration_path %>
    </div>

    <div class="nav-tile">
      <i class="fas fa-sign-out-alt"></i>
      <br>
      <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
    </div>

    <br><br>

  </div>
</div>
<% end %>