config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'd'
  resources :users, :only => [:show]

  get '/messages', to: 'users#messages'

  root to: 'pages#home'

  resources :chats, only: [:create, :show, :index] do
    member do
      patch :favourites
      patch :archive
    end
    collection do
      get :saved
      get :archived
    end

    resources :messages, only: [:create]
  end

  resources :artists do
    collection do
      get :top
    end
    member do
    delete :delete_image_attachment

    end
    resources :services, only: [:new, :create]
    resources :bookings, only: [:new]


    resources :working_hours, only: [:new, :create]


  end

  resources :bookings do
    collection do
      get :all
    end
    member do
      get :selectdate
      get :selecttime
    end
    resources :services_bookings, only: [:new]
  end

  resources :services, only: [:destroy, :edit, :update]
  resources :working_hours, only: [:destroy, :edit, :update]
  resources :bookings, only: [:edit, :update, :create, :destroy, :index ] do
  resources :services_bookings, only: [:create]
  resources :reviews, only: [:new, :create, :index]
    collection do
      get :all
      get :pending
      get :confirmed
      get :declined
      get :cancelled
    end
    member do
      get :details
      patch :confirm
      patch :decline
      patch :cancel
    end
  end

  resources :artists do
    collection do
      get :top
    end
    resources :services, only: [:new, :create]
    resources :bookings, only: [:new, :show]

  end

  resources :bookings do
    resources :services_bookings, only: [:new]
  end

  resources :bookings do
    member do
      get :selectdate
      get :selecttime
    end
  end


  resources :reviews, only: [:edit, :update]
  resources :bookmarks, only: [:index, :create, :destroy] do
    collection { post :sort }
  end
end

app/views/shared/_confirmbooking.html.erb
<div class="d-flex align-items-center justify-content-between p-3 bg-white">

    <%= link_to :back do %>
      <i class="fas fa-chevron-left"></i>
    <% end %>
    <h6>booking details</h6>
<br>
</div>
<br>
<div class="container bottom-padding mt-3">
<div class="d-flex justify-content-between bg-white p-2" style="border-radius: 20px 20px 0px 0px;">
<div style='display: block'>
<br>
<h6> Artist </h6>
<br>
<p> <%= @artist.user.first_name %> <%= @artist.user.last_name %> </p>
<br>
<br>
<h6> Services selected </h6>
<br>
<% @booking.services_bookings.each do |s| %>
   <p><%= "- #{s.service.name} (#{s.quantity})" %></p>
<% end %>
<br>
<h6> Details</h6>
<br>
<% a = 0 %>
<% b = 0 %>
<% @booking.services_bookings.each do |s| %>
   <% a = a + ( s.quantity * s.service.duration ) %>
   <% b = b + ( s.quantity * s.service.price) %>
<% end %>
<p> - <%= a %> minutes </p>
<p> - $<%= b %> </p>
<p> - <%= @booking.start_time.strftime('%H:%M %P   -   %A the %d %B, %y') %> </p>
<br>
<h6>

</div>

<br>
<br>
</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% unless controller_name == "chats" %>
<div class="navbar-main d-flex justify-content-between p-3" style="height: 4rem">

<!-- To Do This Will Be Our Search -->

<div >
<i id="searchbutton" class="fas fa-search"></i>
</div>

<!-- To Do This Will Be Our Bookmarks -->
 <% if user_signed_in? %>
  <%= link_to bookmarks_path do %>
  <i  class="far fa-heart"></i>
<% end %>
<% end %>

<!-- Correct Link  -->

<%= link_to root_path do %>
  <i class="fas fa-home"></i>
<% end %>

<!-- Correct Link  -->

 <% if user_signed_in? %>
 <div data-controller="notification">
<%= link_to chats_path do %>
  <i class="far fa-comments"></i>
  <p data-target="notification.notify" class="badge badge-warning" style="padding: 3px; position: absolute; visibility: hidden;"><%= 0 %></p>
<% end %>
  </div>
<% end %>

<!-- Correct Link  -->

  <% if user_signed_in? %>
    <%= link_to user_path(current_user) do %>
    <i class="far fa-user"></i>
    <% end %>
    <% else %>
    <%= link_to new_user_session_path do %>
    <i class="far fa-user-circle"></i>
  <% end %>
<% end %>

</div>

<% end %>

app/views/shared/_search.html.erb
<div style="width: 100%; display: none" id='searchbar'>
  <div class="search-active-bg">
  </div>
  <div class="search-active-overlay">
<!-- <div class="inputWithIcon">
        <input type="text" placeholder="Search">
        <i class="fas fa-search" aria-hidden="true"></i>
    </div> -->
    <div style="display: flex; justify-content: space-between; margin-bottom: 8px">
    <button class="btn btn-details" id="byLocation" style="width:48%">By Location</button>
    <button class="btn btn-details" id="byName" style="width:48%">By Name</button>
    </div>
    <div style="display: none" id="locationFilter">
    <%= form_tag artists_path, method: :get, class: "in-line" do %>
    <%= text_field_tag :query,
    params[:query],
    class: "location-form",
    placeholder: "Search location"
    %>
    <% end %>
    </div>
    <div style="display: none" id="nameFilter">
    <%= form_tag artists_path, method: :get, class: "in-line" do %>
    <%= text_field_tag :query_artist,
    params[:query_artist],
    class: "artist-form",
    placeholder: "Search name"
    %>
    <% end %>
    </div>
  <!-- <div style="width: 90%; margin-top: 0px">
        <ul class="list-group list-group-horizontal">
          <button type="button" class="btn search-button" style="flex-grow: 1; margin: 8px">Artist</button>
          <button type="button" class="btn search-button" style="flex-grow: 1; margin: 8px">Location</button>
        </ul>
      </div> -->
  </div>
</div>

app/views/shared/_show_accordion.html.erb
<div id="accordion">
  <% @artist.services.each do |service| %>
    <br>
    <div class="accordion-card">
      <div id="heading<%= service.id %>">
        <h6 class="mb-0">
          <button class="btn collapsed font panel-title" data-toggle="collapse" data-target="#collapse<%= service.id %>" aria-expanded="false" aria-controls="collapse<%= service.id %>">
            <%= service.name.capitalize %>
          </button>
        </h6>
      </div>
      <div id="collapse<%= service.id %>" class="collapse" aria-labelledby="heading<%= service.id %>" data-parent="#accordion">
        <div class="card-body">
          <div style="float: right">
            <% if current_user == @artist.user %>
              <%= link_to edit_service_path(service) do %>
                <i class="fas fa-pen-square rating ml-2"></i>
              <% end %>
              <%= link_to service_path(service), method: :delete, class: "delete" do %>
                <i class="fas fa-trash rating ml-2"></i>
              <% end %>
            <% end %>
          </div>
          <strong>Price</strong>
          <br>$<%= service.price %> AUD
          <br><br>
          <strong>Duration</strong>
          <br><%= service.duration %> Minutes
          <br><br>
          <strong>Description</strong>
          <br><%= service.description %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_show_carousel.html.erb
      <div class="cards d-flex ">
        <% @artist.photos.order("position").each do |photo| %>
        <div class="d-block bookmark-img w-100 show-imgs margin-right position-div">
            <%= cl_image_tag photo.key, height: 328, width: 328, crop: :fill, id: "photo-#{photo.blob.id}", class: "h-100", style:'border-radius: 22px;' %>

            <% if user_signed_in? %>
            <% if current_user.has_bookmark?(photo.blob) %>
              <%= link_to bookmark_path(current_user.bookmark_of(photo.blob), anchor: "photo-#{photo.blob.id}"), method: :delete, remote: true do %>
                <i class="fas fa-heart" class="heart" style="background-color: #f6c3e5;position: absolute;bottom: 8px;left: 8px;font-size: 16px;padding: 8px;border-radius: 50%; color: grey;"></i>
              <% end %>
            <% else %>
              <%= link_to bookmarks_path(blob: photo.blob, anchor: "photo-#{photo.blob.id}"), method: :post, remote: true do %>
                <i class="far fa-heart" class="heart" style="background-color: #f6c3e5; position: absolute;bottom: 8px;left: 8px;font-size: 16px;padding: 8px;border-radius: 50%; color: grey;"></i>
              <% end %>
            <% end %>
            <% end %>
        </div>
          <% end %>
        </div>