config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'd'
  resources :users, :only => [:show]

  get '/messages', to: 'users#messages'

  root to: 'pages#home'

  resources :chats, only: [:create, :show, :index] do
    member do
      patch :favourites
      patch :archive
    end
    collection do
      get :saved
      get :archived
    end

    resources :messages, only: [:create]
  end

  resources :artists do
    collection do
      get :top
    end
    member do
    delete :delete_image_attachment

    end
    resources :services, only: [:new, :create]
    resources :bookings, only: [:new]


    resources :working_hours, only: [:new, :create]


  end

  resources :bookings do
    collection do
      get :all
    end
    member do
      get :selectdate
      get :selecttime
    end
    resources :services_bookings, only: [:new]
  end

  resources :services, only: [:destroy, :edit, :update]
  resources :working_hours, only: [:destroy, :edit, :update]
  resources :bookings, only: [:edit, :update, :create, :destroy, :index ] do
  resources :services_bookings, only: [:create]
  resources :reviews, only: [:new, :create, :index]
    collection do
      get :all
      get :pending
      get :confirmed
      get :declined
      get :cancelled
    end
    member do
      get :details
      patch :confirm
      patch :decline
      patch :cancel
    end
  end

  resources :artists do
    collection do
      get :top
    end
    resources :services, only: [:new, :create]
    resources :bookings, only: [:new, :show]

  end

  resources :bookings do
    resources :services_bookings, only: [:new]
  end

  resources :bookings do
    member do
      get :selectdate
      get :selecttime
    end
  end


  resources :reviews, only: [:edit, :update]
  resources :bookmarks, only: [:index, :create, :destroy] do
    collection { post :sort }
  end
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :artist
  has_many :messages, dependent: :destroy
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
    @chats = if current_user.artist
      Chat.where(artist: current_user.artist, artist_archive: false).or(Chat.where(user: current_user, user_archive: false)).order('created_at DESC')
    else
      Chat.where(user: current_user, user_archive: false).order('created_at DESC')
    end
  end

  def create
    @chat = Chat.new
    @chat.user = current_user
    @chat.artist = Artist.find(params[:format])
    if @chat.save
     redirect_to chat_path(@chat)
   end
  end

  def show
    @chat = Chat.find(params[:id])
    @messages = @chat.messages.order('created_at')
    @message = Message.new
    @messages_received = @chat.messages.where.not(user: current_user)
    @messages_received.update_all(read: true)
  end

  def archived
    @chats = if current_user.artist
      Chat.where(artist: current_user.artist, artist_archive: true).or(Chat.where(user: current_user, user_archive: true)).order('created_at DESC')
    else
      Chat.where(user: current_user, user_archive: true).order('created_at DESC')
    end
  end

  def saved
    @chats = if current_user.artist
      Chat.where(artist: current_user.artist, artist_favourite: true, artist_archive: false).or(Chat.where(user: current_user, user_favourite: true, user_archive: false)).order('created_at DESC')
    else
      Chat.where(user: current_user, user_favourite: true, user_archive: false).order('created_at DESC')
    end
  end

  def favourites
    @chat = Chat.find(params[:id])
    toggle_favourites(@chat)
    if @chat.save
      redirect_to request.referrer
    else
      render :show
    end
  end

  def archive
    @chat = Chat.find(params[:id])
    toggle_archive(@chat)
    if @chat.save
      redirect_to request.referrer
    else
      render :show
    end
  end

  def toggle_favourites(chat)
    if chat.user == current_user && chat.user_favourite == false
      chat.user_favourite = true
    elsif chat.artist == current_user.artist && chat.artist_favourite == false
      chat.artist_favourite = true
    elsif chat.user == current_user && chat.user_favourite == true
      chat.user_favourite = false
    elsif chat.artist == current_user.artist && chat.artist_favourite == true
      chat.artist_favourite = false
    end
  end

  def toggle_archive(chat)
    if chat.user == current_user && chat.user_archive == false
      chat.user_archive = true,  (chat.user_favourite = false)
    elsif chat.artist == current_user.artist && chat.artist_archive == false
      chat.artist_archive = true, (chat.artist_favourite = false)
    elsif chat.user == current_user && chat.user_archive == true
      chat.user_archive = false
    elsif chat.artist == current_user.artist && chat.artist_archive == true
      chat.artist_archive = false
    end
  end
end

app/views/chats/_chat-nav.html.erb
<div class="d-flex align-items-center justify-content-between p-3 bg-white navbar-main">

  <%= link_to saved_chats_path do %>
  <i class="fas fa-star"></i>
  <% end %>

  <div data-controller="notification">
  <%= link_to chats_path do %>
  <i class="far fa-comments"></i>
  <% end %>
  <p data-target="notification.notify" class="badge badge-warning" style="padding: 3px; position: absolute; visibility: hidden;"><%= 0 %></p>
 </div>

  <%= link_to archived_chats_path do %>
  <i class="fas fa-archive"></i>
  <% end %>

</div>

app/views/chats/archived.html.erb
  <div class="d-flex align-items-center justify-content-between p-3 bg-white">
    <%= link_to :back do %>
    <i class="fas fa-chevron-left"></i>
  <% end %>

  <h6 class = "text-center"> archived messages </h6>
  <%= link_to user_path(current_user) do %>
  <%= cl_image_tag current_user.photo.key, height: 48, width: 48, gravity: :face, crop: :fill, radius: :max, class: "rounded-circle" %>
  <% end %>
  </div>
<div class="container mt-3">

<div class="chats">
  <% if @chats.empty? %>
  <div class="empty-chat-index">
  <i class="fas fa-archive"></i>
  <h6 >you don't have any archived messages... </h6>
  </div>
  <% end %>

  <!-- --------------------------------------- -->

<% @chats.each do |chat| %>
<% if chat.messages.present? %>


<!-- current user = chat.user HTML -->
<% if chat.user == current_user %>

<div class="chat-box shadow d-flex justify-content-between p-2 mb-2 align-content-center">
  <div class="d-flex">
    <%= link_to chat_path(chat, anchor: "message-#{chat.messages.last.id}") do %>
    <%= cl_image_tag chat.artist.user.photo.key, height: 64, width: 64, gravity: :face, crop: :fill, radius: :max, class: "rounded-circle mr-1" %>
    <% end %>
      <div class="chat-content">
        <div class="dropdown dropdown-menu-right">
        <button class="btn btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= chat.artist.user.username %>
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">

           <%= link_to chat_path(chat, anchor: "message-#{chat.messages.last.id}"), class: "dropdown-item" do %>
          <i class="fas fa-comment"></i> message
          <% end %>

          <%= link_to archive_chat_path(chat), method: :patch, class: "dropdown-item" do%>
            <i class="fas fa-archive"></i> add to inbox
          <% end %>

          <%= link_to artist_path(chat.artist), class: "dropdown-item" do%>
          <i class="fas fa-user"></i> view profile
          <% end %>


        </div>
      </div>
        <p><%= chat.messages.last.content[0..52] %>
         <% if chat.messages.last.content.length > 52 %>
         ...
         <% end %>
      </p>
    </div>
      </div>
      <div class="message-time">
      <% if Time.now - 86400 < chat.messages.last.created_at %>
        <h6 class="text-right"><%= chat.messages.last.created_at.strftime("%l %M %p") %></h6>
      <% elsif Time.now - 86400 > chat.messages.last.created_at && Time.now - 604800 < chat.messages.last.created_at %>
        <h6 class="text-right"><%= chat.messages.last.created_at.strftime("%a") %></h6>
      <% else %>
       <h6 class="text-right"><%= chat.messages.last.created_at.strftime("%e %b %y") %></h6>
      <% end %>




    </div>
  </div>
  <% else %>

  <!-- --------------------------------------- -->
  <!-- current_user.artist == chat.artist HTML -->
  <div class="chat-box d-flex justify-content-between p-2 mb-2 align-content-center">
    <div class="d-flex">
    <%= link_to chat_path(chat, anchor: "message-#{chat.messages.last.id}") do %>
      <%= cl_image_tag chat.user.photo.key, height: 64, width: 64, gravity: :face, crop: :fill, radius: :max, class: "rounded-circle mr-1" %>
    <% end %>
     <div class="chat-content">
       <div class="dropdown dropdown-menu-right">
       <button class="btn btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= chat.user.username %>
       </button>
       <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">


         <%= link_to chat_path(chat, anchor: "message-#{chat.messages.last.id}"), class: "dropdown-item" do %>
         <i class="fas fa-comment"></i> message
         <% end %>

         <%= link_to archive_chat_path(chat), method: :patch, class: "dropdown-item" do%>
           <i class="fas fa-archive"></i> add to inbox
         <% end %>

          <% if chat.user.artist.present? %>
           <%= link_to artist_path(chat.user.artist), class: "dropdown-item" do%>
             <i class="fas fa-user"></i> view profile
           <% end %>
         <% end %>
       </div>
     </div>


      <p><%= chat.messages.last.content[0..52] %>
        <% if chat.messages.last.content.length > 52 %>
         ...
         <% end %>
       </p>
     </div>
       </div>
      <div class="message-time">
      <% if Time.now - 86400 < chat.messages.last.created_at %>
        <h6 class="text-right"><%= chat.messages.last.created_at.strftime("%l %M %p") %></h6>
      <% elsif Time.now - 86400 > chat.messages.last.created_at && Time.now - 604800 < chat.messages.last.created_at %>
        <h6 class="text-right"><%= chat.messages.last.created_at.strftime("%a") %></h6>
      <% else %>
       <h6 class="text-right"><%= chat.messages.last.created_at.strftime("%e %b %y") %></h6>
      <% end %>
    </div>
  </div>
  <% end %>

    <!-- --------------------------------------- -->
<% end %>
<% end %>
</div>
</div>

<!-- bottom navbar -->

<%= render 'chat-nav' %>

  <!-- --------------------------------------- -->

app/views/chats/index.html.erb
  <!-- header -->

  <div class="d-flex align-items-center justify-content-between p-3 bg-white">
    <%= link_to artists_path do %>
    <i class="fas fa-chevron-left"></i>
  <% end %>

  <h6 class = "text-center"> messages </h6>
  <%= link_to user_path(current_user) do %>
  <%= cl_image_tag current_user.photo.key, height: 48, width: 48, gravity: :face, crop: :fill, radius: :max, class: "rounded-circle" %>
  <% end %>
  </div>

<div class="container mt-3">
  <!-- --------------------------------------- -->
  <!-- chat empty condition -->

<div class="chats">
  <% if @chats.empty? %>
  <div class="empty-chat-index">
  <i class="far fa-bell"></i>
  <h6 >you don't have any messages yet... </h6>
  </div>
  <% end %>
  <!-- --------------------------------------- -->

<% @chats.each do |chat| %>
<% if chat.messages.present? %>


<!-- current user = chat.user HTML -->
<% if chat.user == current_user %>

<div class="chat-box shadow d-flex justify-content-between p-2 mb-2 align-content-center">
  <div class="d-flex">
    <%= link_to chat_path(chat, anchor: "message-#{chat.messages.order('created_at').last.id}") do %>
    <%= cl_image_tag chat.artist.user.photo.key, height: 64, width: 64, gravity: :face, crop: :fill, radius: :max, class: "rounded-circle mr-1" %>
    <% end %>
      <div class="chat-content">
        <div class="dropdown dropdown-menu-right">
        <button class="btn btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= chat.artist.user.username %>
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">

          <%= link_to chat_path(chat, anchor: "message-#{chat.messages.order('created_at').last.id}"), class: "dropdown-item" do %>
          <i class="fas fa-comment"></i> message
          <% end %>

          <% if chat.user_favourite == true %>
            <%= link_to favourites_chat_path(chat), method: :patch, class: "dropdown-item" do %>
           <i class="fas fa-star"></i> mark as not important
          <% end %>
          <% else %>
          <%= link_to favourites_chat_path(chat), method: :patch, class: "dropdown-item" do%>
          <i class="far fa-star"></i> mark as important
          <% end %>
          <% end %>
          <%= link_to artist_path(chat.artist), class: "dropdown-item" do%>
          <i class="fas fa-user"></i> view profile
          <% end %>
          <%= link_to archive_chat_path(chat), method: :patch, class: "dropdown-item" do%>
            <i class="fas fa-archive"></i> archive
          <% end %>
        </div>
      </div>
        <p><%= chat.messages.order('created_at').last.content[0..40] %>
         <% if chat.messages.order('created_at').last.content.length > 40 %>
         ...
         <% end %>
      </p>
    </div>
      </div>
      <div class="message-time">
      <% if Time.now - 86400 < chat.messages.order('created_at').last.created_at %>
        <h6 class="text-right"><%= chat.messages.order('created_at').last.created_at.strftime("%l %M %p") %></h6>
      <% elsif Time.now - 86400 > chat.messages.order('created_at').last.created_at && Time.now - 604800 < chat.messages.order('created_at').last.created_at %>
        <h6 class="text-right"><%= chat.messages.order('created_at').last.created_at.strftime("%a") %></h6>
      <% else %>
       <h6 class="text-right"><%= chat.messages.order('created_at').last.created_at.strftime("%e %b %y") %></h6>
      <% end %>




    </div>
  </div>
  <% else %>

  <!-- --------------------------------------- -->
  <!-- current_user.artist == chat.artist HTML -->
  <div class="chat-box d-flex justify-content-between p-2 mb-2 align-content-center">
    <div class="d-flex">
    <%= link_to chat_path(chat, anchor: "message-#{chat.messages.order('created_at').last.id}") do %>
      <%= cl_image_tag chat.user.photo.key, height: 64, width: 64, gravity: :face, crop: :fill, radius: :max, class: "rounded-circle mr-1" %>
    <% end %>
     <div class="chat-content">
       <div class="dropdown dropdown-menu-right">
       <button class="btn btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= chat.user.username %>
       </button>
       <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">

    <%= link_to chat_path(chat, anchor: "message-#{chat.messages.order('created_at').last.id}"), class: "dropdown-item" do %>
    <i class="fas fa-comment"></i> message
    <% end %>

    <% if chat.artist_favourite == true %>

     <%= link_to favourites_chat_path(chat), method: :patch, class: "dropdown-item" do %>
       <i class="fas fa-star"></i> mark as not important
     <% end %>
   <% else %>
     <%= link_to favourites_chat_path(chat), method: :patch, class: "dropdown-item" do%>
       <i class="far fa-star"></i> mark as important
     <% end %>
   <% end %>

   <% if chat.user.artist.present? %>
    <%= link_to artist_path(chat.user.artist), class: "dropdown-item" do%>
      <i class="fas fa-user"></i> view profile
    <% end %>
  <% end %>

        <%= link_to archive_chat_path(chat), method: :patch, class: "dropdown-item" do%>
            <i class="fas fa-archive"></i> archive
        <% end %>
       </div>
     </div>


      <p><%= chat.messages.order('created_at').last.content[0..40] %>
        <% if chat.messages.order('created_at').last.content.length > 40 %>
         ...
         <% end %>
       </p>
     </div>
       </div>
      <div class="message-time">
      <% if Time.now - 86400 < chat.messages.order('created_at').last.created_at %>
        <h6 class="text-right"><%= chat.messages.order('created_at').last.created_at.strftime("%l %M %p") %></h6>
      <% elsif Time.now - 86400 > chat.messages.order('created_at').last.created_at && Time.now - 604800 < chat.messages.order('created_at').last.created_at %>
        <h6 class="text-right"><%= chat.messages.order('created_at').last.created_at.strftime("%a") %></h6>
      <% else %>
       <h6 class="text-right"><%= chat.messages.order('created_at').last.created_at.strftime("%e %b %y") %></h6>
      <% end %>
    </div>
  </div>
  <% end %>

    <!-- --------------------------------------- -->
<% end %>
<% end %>
</div>
</div>
</div>

<!-- bottom navbar -->

<%= render 'chat-nav' %>

  <!-- --------------------------------------- -->

app/views/chats/saved.html.erb
  <div class="d-flex align-items-center justify-content-between p-3 bg-white">
    <%= link_to :back do %>
    <i class="fas fa-chevron-left"></i>
  <% end %>

  <h6 class = "text-center"> important messages </h6>
  <%= link_to user_path(current_user) do %>
  <%= cl_image_tag current_user.photo.key, height: 48, width: 48, gravity: :face, crop: :fill, radius: :max, class: "rounded-circle" %>
  <% end %>
  </div>
<div class="container mt-3">

<div class="chats">
  <% if @chats.empty? %>
  <div class="empty-chat-index">
  <i class="fas fa-star"></i>
  <h6 >you don't have any messages marked as important... </h6>
  </div>
  <% end %>

  <!-- --------------------------------------- -->

<% @chats.each do |chat| %>
<% if chat.messages.present? %>


<!-- current user = chat.user HTML -->
<% if chat.user == current_user %>

<div class="chat-box shadow d-flex justify-content-between p-2 mb-2 align-content-center">
  <div class="d-flex">
    <%= link_to chat_path(chat, anchor: "message-#{chat.messages.last.id}") do %>
    <%= cl_image_tag chat.artist.user.photo.key, height: 64, width: 64, gravity: :face, crop: :fill, radius: :max, class: "rounded-circle mr-1" %>
    <% end %>
      <div class="chat-content">
        <div class="dropdown dropdown-menu-right">
        <button class="btn btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= chat.artist.user.username %>
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">

          <%= link_to chat_path(chat, anchor: "message-#{chat.messages.last.id}"), class: "dropdown-item" do %>
          <i class="fas fa-comment"></i> message
          <% end %>

          <% if chat.user_favourite == true %>
            <%= link_to favourites_chat_path(chat), method: :patch, class: "dropdown-item" do %>
           <i class="fas fa-star"></i> mark as not important
          <% end %>
          <% else %>
          <%= link_to favourites_chat_path(chat), method: :patch, class: "dropdown-item" do%>
          <i class="far fa-star"></i> mark as important
          <% end %>
          <% end %>
          <%= link_to artist_path(chat.artist), class: "dropdown-item" do%>
          <i class="fas fa-user"></i> view profile
          <% end %>
          <%= link_to archive_chat_path(chat), method: :patch, class: "dropdown-item" do%>
            <i class="fas fa-archive"></i> archive
        <% end %>
        </div>
      </div>
        <p><%= chat.messages.last.content[0..52] %>
         <% if chat.messages.last.content.length > 52 %>
         ...
         <% end %>
      </p>
    </div>
      </div>
      <div class="message-time">
      <% if Time.now - 86400 < chat.messages.last.created_at %>
        <h6 class="text-right"><%= chat.messages.last.created_at.strftime("%l %M %p") %></h6>
      <% elsif Time.now - 86400 > chat.messages.last.created_at && Time.now - 604800 < chat.messages.last.created_at %>
        <h6 class="text-right"><%= chat.messages.last.created_at.strftime("%a") %></h6>
      <% else %>
       <h6 class="text-right"><%= chat.messages.last.created_at.strftime("%e %b %y") %></h6>
      <% end %>




    </div>
  </div>
  <% else %>

  <!-- --------------------------------------- -->
  <!-- current_user.artist == chat.artist HTML -->
  <div class="chat-box d-flex justify-content-between p-2 mb-2 align-content-center">
    <div class="d-flex">
    <%= link_to chat_path(chat, anchor: "message-#{chat.messages.last.id}") do %>
      <%= cl_image_tag chat.user.photo.key, height: 64, width: 64, gravity: :face, crop: :fill, radius: :max, class: "rounded-circle mr-1" %>
    <% end %>
     <div class="chat-content">
       <div class="dropdown dropdown-menu-right">
       <button class="btn btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= chat.user.username %>
       </button>
       <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <%= link_to chat_path(chat, anchor: "message-#{chat.messages.last.id}"), class: "dropdown-item" do %>
        <i class="fas fa-comment"></i> message
        <% end %>

    <% if chat.artist_favourite == true %>
     <%= link_to favourites_chat_path(chat), method: :patch, class: "dropdown-item" do %>
       <i class="fas fa-star"></i> mark as not important
     <% end %>
   <% else %>
     <%= link_to favourites_chat_path(chat), method: :patch, class: "dropdown-item" do%>
       <i class="far fa-star"></i> mark as important
     <% end %>
   <% end %>

   <% if chat.user.artist.present? %>
    <%= link_to artist_path(chat.user.artist), class: "dropdown-item" do%>
      <i class="fas fa-user"></i> view profile
    <% end %>
  <% end %>

         <%= link_to archive_chat_path(chat), method: :patch, class: "dropdown-item" do%>
            <i class="fas fa-archive"></i> archive
        <% end %>
         </a>
       </div>
     </div>


      <p><%= chat.messages.last.content[0..52] %>
        <% if chat.messages.last.content.length > 52 %>
         ...
         <% end %>
       </p>
     </div>
       </div>
      <div class="message-time">
      <% if Time.now - 86400 < chat.messages.last.created_at %>
        <h6 class="text-right"><%= chat.messages.last.created_at.strftime("%l %M %p") %></h6>
      <% elsif Time.now - 86400 > chat.messages.last.created_at && Time.now - 604800 < chat.messages.last.created_at %>
        <h6 class="text-right"><%= chat.messages.last.created_at.strftime("%a") %></h6>
      <% else %>
       <h6 class="text-right"><%= chat.messages.last.created_at.strftime("%e %b %y") %></h6>
      <% end %>
    </div>
  </div>
  <% end %>

    <!-- --------------------------------------- -->
<% end %>
<% end %>
</div>
</div>

<!-- bottom navbar -->

<%= render 'chat-nav' %>

  <!-- --------------------------------------- -->

app/views/chats/show.html.erb
<div class="d-flex justify-content-between align-items-center p-3 bg-white chat-header">
  <%= link_to chats_path do %>
    <i class="fas fa-chevron-left"></i>
  <% end %>
  <% if @chat.user == current_user %>
    <h6 class="text-center"><%= @chat.artist.user.username %></h6>
    <%= link_to artist_path(@chat.artist) do %>
    <%= cl_image_tag @chat.artist.user.photo.key, height: 48, width: 48, gravity: :face, crop: :fill, radius: :max, class: "rounded-circle" %>
    <% end %>
    <% else %>
    <h6 class="text-center"><%= @chat.user.username %></h6>
    <% if @chat.user.artist.present? %>
    <%= link_to artist_path(@chat.user.artist) do %>
    <%= cl_image_tag @chat.user.photo.key, height: 48, width: 48, gravity: :face, crop: :fill, radius: :max, class: "rounded-circle" %>
    <% end %>
    <% else %>
    <%= cl_image_tag @chat.user.photo.key, height: 48, width: 48, gravity: :face, crop: :fill, radius: :max, class: "rounded-circle" %>
  <% end %>
  <% end %>
</div>


<div id="messages" data-chat-id="<%= @chat.id %>">

<% @messages.order('created_at').each do |message| %>

<div class="message-container chat-box shadow d-flex justify-content-between p-2 mb-2 align-content-center user-<%= message.user == current_user %>" id="message-<%= message.id %>">
<div class="d-flex content-container">
  <% if message.user.artist.present? %>
  <%= link_to artist_path(message.user.artist) do %>
  <%= cl_image_tag message.user.photo.key, height: 48, width: 48, gravity: :face, crop: :fill, radius: :max, class: "rounded-circle mr-3" %>
  <% end %>
  <% else %>
  <%= cl_image_tag message.user.photo.key, height: 48, width: 48, gravity: :face, crop: :fill, radius: :max, class: "rounded-circle mr-3" %>
  <% end %>
<div class="chat-content">
<h6><%= message.user.username%></h6>
<p><%= raw message.content %></p>
</div>
</div>
  <div class="message-time">
  <% if Time.now - 86400 < message.created_at %>
    <h6 class="text-right"><%= message.created_at.strftime("%l %M %p") %></h6>
  <% elsif Time.now - 86400 > message.created_at && Time.now - 604800 < message.created_at %>
    <h6 class="text-right"><%= message.created_at.strftime("%a") %></h6>
  <% else %>
   <h6 class="text-right"><%= message.created_at.strftime("%e %b %y") %></h6>
  <% end %>
</div>
</div>

<% end %>
</div>



<%= simple_form_for [@chat, @message], remote: true do |f| %>
  <%= f.input :content, label: false, placeholder: "Message..." %>
  <%= button_tag type: 'submit', class: "btn btn-warning send-radius" do %>
      <i class="fa fa-paper-plane" aria-hidden="true"></i>
  <% end %>
<% end %>